name: Build manifests and push

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      # To create an artifact
      actions: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build manifests
        run: nix-shell --run './build.sh kubespray.jsonnet'
      - name: Archive manifests
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: manifests
          path: |
            LICENSE
            kustomization.yaml
            manifests/
          if-no-files-found: error
  publish:
    permissions:
      actions: read
      contents: write
    needs: compile
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download manifests Artifact
        uses: actions/download-artifact@v2
        with:
          name: manifests
      - name: Zip manifests
        run: zip -r manifests.zip kustomization.yaml LICENSE manifests
      - name: Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v1
        with:
          # Not supported yet
          # fail_on_unmatched_files: true
          files: manifests.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
